depth_publisher:
  ros__parameters:
    box_count: 2
    box_size: [1.0, 1.0, 0.5]
    box_positions:
      box_0: [0.0, 0.0, 0.0]
      box_1: [0.0, 5.0, 0.0]
    terrain:
      file_path: assets/flatPlane_200x200m_80kTriangles.obj

meshes_rviz:
  ros__parameters:
    box_count: 2
    box_size: [1.0, 1.0, 0.5]
    box_positions:
      box_0: [0.0, 0.0, 0.0]
      box_1: [0.0, 5.0, 0.0]
    terrain:
      file_path: assets/flatPlane_200x200m_80kTriangles.obj
