depth_publisher:
  ros__parameters:
    box_count: 3
    box_size: [1.0, 1.0, 0.5]
    box_positions:
      box_0: [0.0, 10.0, 0.0]
      box_1: [0.0, 20.0, 0.0]
      box_2: [2.0, 15.0, 0.0]
    terrain:
      file_path: assets/seabed_200x200m.obj

meshes_rviz:
  ros__parameters:
    box_count: 3
    box_size: [1.0, 1.0, 0.5]
    box_positions:
      box_0: [0.0, 10.0, 0.0]
      box_1: [0.0, 20.0, 0.0]
      box_2: [2.0, 15.0, 0.0]
    terrain:
      file_path: assets/seabed_200x200m.obj
